// <auto-generated />
using EfCore.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ProjectTo_Issue.Migrations
{
    [DbContext(typeof(MyAppContext))]
    partial class MyAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799");

            modelBuilder.Entity("EFCore.Models.Cat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CatBreedId");

                    b.Property<int>("MeowLoudness");

                    b.Property<string>("Name");

                    b.Property<int>("TailLength");

                    b.HasKey("Id");

                    b.HasIndex("CatBreedId");

                    b.ToTable("Cat");
                });

            modelBuilder.Entity("EFCore.Models.CatBreed", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BreedName");

                    b.HasKey("Id");

                    b.ToTable("CatBreed");
                });

            modelBuilder.Entity("EFCore.Models.Cat", b =>
                {
                    b.HasOne("EFCore.Models.CatBreed", "Breed")
                        .WithMany("Cats")
                        .HasForeignKey("CatBreedId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
